# Generated by Django 4.2.4 on 2023-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalculator', '0002_user_saved_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='projectcalculator.project'),
        ),
    ]
