# Generated by Django 4.2.4 on 2023-08-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalculator', '0003_alter_user_saved_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='descrption',
            new_name='description',
        ),
    ]
