# Generated by Django 4.2.4 on 2023-08-12 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalculator', '0004_rename_descrption_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
