# Generated by Django 4.2.4 on 2023-08-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalculator', '0006_rename_owner_project_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterialSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_qty', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcalculator.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcalculator.project')),
            ],
        ),
    ]
