# Generated by Django 4.2.4 on 2023-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalculator', '0008_remove_project_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='projects', through='projectcalculator.ProjectMaterialSet', to='projectcalculator.material'),
        ),
    ]
